default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: chatroom_development
  # username:
  # password:

test:
  <<: *default
  database: chatroom_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
